services:
  db:
    image: postgres:16-alpine
    container_name: usersvc-db
    environment:
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: user_service_pass
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service_user -d user_service_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  usersvc:
    build: .
    container_name: usersvc-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://user_service_user:user_service_pass@db:5432/user_service_db
      JWT_SECRET_KEY: "change-this-secret-later"
      FLASK_ENV: production
    ports:
      - "5001:5000"
